name: Import CSV to PostgreSQL

on:
  workflow_dispatch:

jobs:
  import_csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

#      - name: Install dependencies
#        run: pip install -r requirements.txt

      - name: Import CSV
        env:
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        run: python generate_mozc_dict.py

